### ISSUE TITLE
Amazing Work! Well done!

### ISSUE THREAD

**Issue by ayushmankumar7** [Soumyajit-Dey-660/automate_change_wallpaper#1]

**Comment by ayushmankumar7** [comment]
The files are organized well. Nice approach! Liked it! 
How did you feel about our first challenge?

**Comment by Soumyajit-Dey-660** [comment]
Thanks!
It was a fun challenge. I really liked it!

PS: I am not a student though. I am a 2020 CSE passout from BPPIMT.
Currently at ThirdEye as a jr. Data Engineer.

**Comment by ayushmankumar7** [comment]
Haha! Amazing! 😁👌
